In [ ]:
# Group 8
#Amer Alhamwi 15976814
#Wael Hamid   80105687# Group 8


In [40]:
#This cell imports needed libraries for image processing,
#logistic regression modeling, and evaluating using confusion matrix and accuracy score
import os
import numpy as np
from PIL import Image  # Already importing 'Image' from 'PIL'
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt


In [41]:
#This cell defines the folder to load images from, it also crops the images for a better training accuracy
#and lastly assigning labels(classfaing) based on the first letter of the image names and stores them into an array.  


# Declare the two folders names for image files
path = "C:/Users/Admin/Desktop/ENGR 418/Assignments/Project_Stage_1"

def test_function(path):
    folder_training = os.path.join(path,"training")
    folder_testing = os.path.join(path,"testing")
    
    return folder_training, folder_testing


# Define the function before calling it
def get_image_data(folder):
    x = []
    y = []

    for pic in os.listdir(f"{folder}/"):
        # opening image using image from PIL
        image = Image.open(f"{folder}/{pic}").convert("L")
        # Crop the images to the center to make it more accurate
        top = int(np.floor(image.height / 4))
        bottom = int(np.ceil(image.height * (3 / 4)))
        left = int(np.floor(image.width / 4))
        right = int(np.ceil(image.width * (3 / 4)))
        #print(image.size)

        # new image is about [500*500] pixels
        cropped_image = image.crop((left, top, right, bottom))

        # resizing images to 64*64 pixels (4096)
        resized_image = cropped_image.resize((64, 64))
        
        data = np.asarray(resized_image)  # Convert image to an array
        
        vec = np.hstack(data)  # Flatten 2D image to a 1D array
        
        x.append(vec)  # Append the flattened image data to the list

        # Assign classes based on first letter/number of the image name
        if str.lower(pic[0]) == "c":
            y.append(0)  # Circle
        elif str.lower(pic[0]) == "r":
            y.append(1)  # Rectangle
        elif str.lower(pic[0]) == "2":
            y.append(2)  # 2x1 Rectangle
        else:
            y.append(3)  # Square 

    x = np.array(x)  # Convert to numpy array
    y = np.array(y)  # Convert to numpy array
 
    return x, y



In [42]:
# This cell loads the training data, trains a Logistic 
# Regression model with the training set, and then
# evaluates the model by predicting on the same training data.

# Set paths for training and testing folders based on the project path
folder_training, folder_testing= test_function(path)

# Load the training data
x1_train, y1_train = get_image_data(folder_training)

# Train the Logistic Regression model 
model = LogisticRegression(solver='lbfgs', max_iter=1000)  # Increase max_iter to 1000 or more

#print(f"Data from first directory: {x1_train.shape}, Labels: {y1_train.shape}")

# Train the Logistic Regression model 
model = LogisticRegression(solver='lbfgs', max_iter=1000)  # Increase max_iter to 1000 
model.fit(x1_train, y1_train)

y_pred1 = model.predict(x1_train)

print("Accuracy:", accuracy_score(y1_train, y_pred1))
print("Confusion Matrix:\n", confusion_matrix(y1_train, y_pred1))

Accuracy: 1.0
Confusion Matrix:
 [[36  0  0  0]
 [ 0 36  0  0]
 [ 0  0 36  0]
 [ 0  0  0 36]]


In [43]:
# This cell loads the testing data, and starts predictiong 
# based on the new test data and then evaluates the model 
# by predicting on testing data.
# Load the testing data
x1_test, y1_test = get_image_data(folder_testing)

# Predict on the test set
y_pred2 = model.predict(x1_test)

# Print the accuracy and confusion matrix
print("Accuracy:", accuracy_score(y1_test, y_pred2))
print("Confusion Matrix:\n", confusion_matrix(y1_test, y_pred2))

Accuracy: 0.9722222222222222
Confusion Matrix:
 [[17  0  0  1]
 [ 0 18  0  0]
 [ 0  0 18  0]
 [ 1  0  0 17]]
