In [54]:
import os
import numpy as np
from PIL import Image  # Already importing 'Image' from 'PIL'
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt


In [57]:


# Declare the two directory names for your image files
rel_dir1 = "C:/Users/Admin/Desktop/ENGR 418/Assignments/Project_Stage_1/training"
rel_dir2 = "C:/Users/Admin/Desktop/ENGR 418/Assignments/Project_Stage_1/testing"

x1_train, y1_train = get_image_data(rel_dir1)
x1_test, y1_test = get_image_data(rel_dir2)
#print(f"Data from first directory: {x1_train}, Labels: {y1_train}")

# Next, we need to train the model 
model = LogisticRegression(solver='lbfgs', max_iter=1000)  # Increase max_iter to 1000 or more
model.fit(x1_train,y1_train)

y_pred = model.predict(x1_test)
print(accuracy_score(y1_test,y_pred))
print(confusion_matrix(y1_test,y_pred))

def get_image_data(fileName):

    x = []
    y = []

    for pic in os.listdir(f"{fileName}/"):
        # Use 'Image' since it was imported directly from 'PIL'
        image = Image.open(f"{fileName}/{pic}").convert("L")
        
        image = Image.fromarray(np.array(image)[
            int(np.floor(image.height / 4)) : int(np.ceil(3 * image.height / 4)),
            int(np.floor(image.width / 4)) : int(np.ceil(3 * image.width / 4))
        ])
        image = image.resize((64,64))  # Resize the image to 64x64 pixels
        
        data = np.asarray(image)  # Convert image to numpy array
        
        vec = np.hstack(data)  # Flatten 2D image to 1D array
        
        x.append(vec)  # Append the flattened image data to the list

        # Assign a label based on the first letter of the filename
        if str.lower(pic[0]) == "c":
            y.append(0)  # Circle
        elif str.lower(pic[0]) == "r":
            y.append(1)  # Rectangle
        elif str.lower(pic[0]) == "2":
            y.append(2)  # 2x1 Rectangle
        else:
            y.append(3)  # Square or other shape

    x = np.array(x)  # Convert to numpy array
    y = np.array(y)  # Convert to numpy array
    
    return x, y


0.9722222222222222
[[17  0  0  1]
 [ 0 18  0  0]
 [ 0  0 18  0]
 [ 1  0  0 17]]
